# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fn < Formula
  desc ""
  homepage ""
  version "0.0.42"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/namespacelabs/foundation/releases/download/v0.0.42/fn_0.0.42_darwin_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "be24b5b7309add44d4eef5e93d23b0f7f5cfa05557b7759008355faffa69edb1"

      def install
        bin.install "fn"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/namespacelabs/foundation/releases/download/v0.0.42/fn_0.0.42_darwin_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "13f1ff7e20c254fa7d491b500d52a97880122e80bf8a5ca88bf2af51300c2412"

      def install
        bin.install "fn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/namespacelabs/foundation/releases/download/v0.0.42/fn_0.0.42_linux_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "1ea8b776b24228c1f48c0db4a80317576fad6046297298b1174e2dc1be6f9553"

      def install
        bin.install "fn"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/namespacelabs/foundation/releases/download/v0.0.42/fn_0.0.42_linux_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "bdcac64ea6a989c8746f04cddef74307ab179ee9349ec1fc4f101771148ccff1"

      def install
        bin.install "fn"
      end
    end
  end
end
