# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ns < Formula
  desc "Developer platform with a unified experience from development to production."
  homepage "https://namespacelabs.com/"
  version "0.0.181"

  on_macos do
    if Hardware::CPU.arm?
      url "https://get.namespace.so/packages/ns/v0.0.181/ns_0.0.181_darwin_arm64.tar.gz"
      sha256 "4a96c115bec4263dd1977632218655fc5ad72955f1d2b9270f12022041203c1b"

      def install
        bin.install "ns"
      end
    end
    if Hardware::CPU.intel?
      url "https://get.namespace.so/packages/ns/v0.0.181/ns_0.0.181_darwin_amd64.tar.gz"
      sha256 "77ab001c96ea21d8b7c9430291b976e68689995c76448b0e20818fb738ec13b6"

      def install
        bin.install "ns"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://get.namespace.so/packages/ns/v0.0.181/ns_0.0.181_linux_arm64.tar.gz"
      sha256 "89ff339743deecef28ac968dfca282676a54e512c9709269a1af37f8b7adb676"

      def install
        bin.install "ns"
      end
    end
    if Hardware::CPU.intel?
      url "https://get.namespace.so/packages/ns/v0.0.181/ns_0.0.181_linux_amd64.tar.gz"
      sha256 "a0d933c59b83fa88d64e94f48f443c4e89d2aa85b5f01579e81db6da8ef55622"

      def install
        bin.install "ns"
      end
    end
  end

  def caveats
    <<~EOS
      Note: ns collects usage telemetry. This data helps us build a better
      platform for you. You can learn more at https://namespace.so/telemetry.

      Check out our examples at https://namespace.so/docs#examples to get started.
    EOS
  end
end
