# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nsboot < Formula
  desc "Developer platform with a unified experience from development to production."
  homepage "https://namespacelabs.com/"
  version "0.0.50"

  on_macos do
    if Hardware::CPU.arm?
      url "https://ns-releases.s3.us-east-2.amazonaws.com/nsboot/v0.0.50/nsboot_0.0.50_darwin_arm64.tar.gz"
      sha256 "08d47e452a5911382cca2d36516c3ad4db29ce318ea87461af1bf3fe8c5ab740"

      def install
        libexec.install "nsboot" bin.install_symlink libexec/"nsboot" => "ns"
      end
    end
    if Hardware::CPU.intel?
      url "https://ns-releases.s3.us-east-2.amazonaws.com/nsboot/v0.0.50/nsboot_0.0.50_darwin_amd64.tar.gz"
      sha256 "e27ca3aefb03c7ae373fed01b1ff4b8f45fa042b5e8121972afd9d56fd828e82"

      def install
        libexec.install "nsboot" bin.install_symlink libexec/"nsboot" => "ns"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://ns-releases.s3.us-east-2.amazonaws.com/nsboot/v0.0.50/nsboot_0.0.50_linux_arm64.tar.gz"
      sha256 "75f0239e81711427dd119db6255bfc0026214b9e501397436f9c2386ffbe3468"

      def install
        libexec.install "nsboot" bin.install_symlink libexec/"nsboot" => "ns"
      end
    end
    if Hardware::CPU.intel?
      url "https://ns-releases.s3.us-east-2.amazonaws.com/nsboot/v0.0.50/nsboot_0.0.50_linux_amd64.tar.gz"
      sha256 "cda1b8d6bae4d298587221304ce3c0784a999e5785936e03d07c31dc5861e154"

      def install
        libexec.install "nsboot" bin.install_symlink libexec/"nsboot" => "ns"
      end
    end
  end
end
