# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nsc < Formula
  desc "Container-optimized cloud infrastructure that just works."
  homepage "https://namespace.so/"
  version "0.0.292"

  on_macos do
    if Hardware::CPU.arm?
      url "https://get.namespace.so/packages/nsc/v0.0.292/nsc_0.0.292_darwin_arm64.tar.gz"
      sha256 "004e31b2eca676b84c4e0dacf350ba26f28c99a5a7dd99f38ed8c7604cdb8cea"

      def install
        bin.install "nsc"
        bin.install "docker-credential-nsc"
      end
    end
    if Hardware::CPU.intel?
      url "https://get.namespace.so/packages/nsc/v0.0.292/nsc_0.0.292_darwin_amd64.tar.gz"
      sha256 "08864342fe3cb44c4c6075b3d140c079defd3af8fdcf7608447bdfe2ca9e63eb"

      def install
        bin.install "nsc"
        bin.install "docker-credential-nsc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://get.namespace.so/packages/nsc/v0.0.292/nsc_0.0.292_linux_arm64.tar.gz"
      sha256 "cf9ad7d24bf04622a9cb9c0a3d7f4b7c1b248b87d768434bc3147956a274c0c8"

      def install
        bin.install "nsc"
        bin.install "docker-credential-nsc"
      end
    end
    if Hardware::CPU.intel?
      url "https://get.namespace.so/packages/nsc/v0.0.292/nsc_0.0.292_linux_amd64.tar.gz"
      sha256 "b0431dd71ad8f87ae33ca01b914d4f98083c541c4e3290ae92a642d36234a9be"

      def install
        bin.install "nsc"
        bin.install "docker-credential-nsc"
      end
    end
  end
end
