# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nsc < Formula
  desc "Container-optimized cloud infrastructure that just works."
  homepage "https://namespace.so/"
  version "0.0.303"

  on_macos do
    if Hardware::CPU.arm?
      url "https://get.namespace.so/packages/nsc/v0.0.303/nsc_0.0.303_darwin_arm64.tar.gz"
      sha256 "179c3161b862b16016a025104b1d2ad98a281c5a149f92c6ff743427f324c832"

      def install
        bin.install "nsc"
        bin.install "docker-credential-nsc"
      end
    end
    if Hardware::CPU.intel?
      url "https://get.namespace.so/packages/nsc/v0.0.303/nsc_0.0.303_darwin_amd64.tar.gz"
      sha256 "0a001a6168ca7f1725100b8e2c5f7fa40c94301a2c6d4f8f3174da2337bf7092"

      def install
        bin.install "nsc"
        bin.install "docker-credential-nsc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://get.namespace.so/packages/nsc/v0.0.303/nsc_0.0.303_linux_arm64.tar.gz"
      sha256 "aa4568254c1852db965bd2d2125a63bcc7edbf6d5b2c6b3045049f0c34f7d9e5"

      def install
        bin.install "nsc"
        bin.install "docker-credential-nsc"
      end
    end
    if Hardware::CPU.intel?
      url "https://get.namespace.so/packages/nsc/v0.0.303/nsc_0.0.303_linux_amd64.tar.gz"
      sha256 "012496468a8c1dacdf85b1ee75968070eca479eb7a1bb70b8ccf20689c7497c2"

      def install
        bin.install "nsc"
        bin.install "docker-credential-nsc"
      end
    end
  end
end
