# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nsc < Formula
  desc "Container-optimized cloud infrastructure that just works."
  homepage "https://namespace.so/"
  version "0.0.281"

  on_macos do
    if Hardware::CPU.arm?
      url "https://get.namespace.so/packages/nsc/v0.0.281/nsc_0.0.281_darwin_arm64.tar.gz"
      sha256 "5eb349542ec76cad42655d51bec5b377092014057ac8dd9a8332c35c28a1a655"

      def install
        bin.install "nsc"
        bin.install "docker-credential-nsc"
      end
    end
    if Hardware::CPU.intel?
      url "https://get.namespace.so/packages/nsc/v0.0.281/nsc_0.0.281_darwin_amd64.tar.gz"
      sha256 "c978385454596b632adcd1d7ed2c7cc9b6c6a7ec940d50f8c37b5e511c07c596"

      def install
        bin.install "nsc"
        bin.install "docker-credential-nsc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://get.namespace.so/packages/nsc/v0.0.281/nsc_0.0.281_linux_arm64.tar.gz"
      sha256 "26251fe4c7abf3cb8400baac15a20e2f9cc8c35cdb7b4a59438857a23af9aeb7"

      def install
        bin.install "nsc"
        bin.install "docker-credential-nsc"
      end
    end
    if Hardware::CPU.intel?
      url "https://get.namespace.so/packages/nsc/v0.0.281/nsc_0.0.281_linux_amd64.tar.gz"
      sha256 "e4c96af7d7c6dae0b821452b1f772df517940cc9e59f039b2a40a79345cc57a8"

      def install
        bin.install "nsc"
        bin.install "docker-credential-nsc"
      end
    end
  end
end
