# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fn < Formula
  desc ""
  homepage ""
  version "0.0.42-snapshot"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/namespacelabs/foundation/releases/download/v0.0.41/fn_0.0.42-snapshot_darwin_arm64.tar.gz"
      sha256 "6e6f8711c6a227bfaccb04b67690989004254330d734fdd26b7c0ab6b7552095"

      def install
        bin.install "fn"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/namespacelabs/foundation/releases/download/v0.0.41/fn_0.0.42-snapshot_darwin_amd64.tar.gz"
      sha256 "1ef528aa2bca1b11d4e4bc0f7cf4e4e98f31b61fe9bed1c57bfcc20ad709f656"

      def install
        bin.install "fn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/namespacelabs/foundation/releases/download/v0.0.41/fn_0.0.42-snapshot_linux_arm64.tar.gz"
      sha256 "dbd618572a4c14be70e594c7da7d355761bde9310b43787fa837ccf526ca8c39"

      def install
        bin.install "fn"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/namespacelabs/foundation/releases/download/v0.0.41/fn_0.0.42-snapshot_linux_amd64.tar.gz"
      sha256 "91568317b72606d4438c988e2f36ac9d3214ff3ee5398e074ce854bf19b84ab1"

      def install
        bin.install "fn"
      end
    end
  end
end
