# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class Fn < Formula
  desc ""
  homepage ""
  version "0.0.42"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/namespacelabs/foundation/releases/download/v0.0.42/fn_0.0.42_darwin_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c16bd5c7bc7d4fe9ed20e4b3eec969d1db2007f70f3ba663399eae08a6705e0e"

      def install
        bin.install "fn"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/namespacelabs/foundation/releases/download/v0.0.42/fn_0.0.42_darwin_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f1366f8f17c6a33c6420e5bdc91cf4a8571f4c295dacb2ad692a26d453b5d9c5"

      def install
        bin.install "fn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/namespacelabs/foundation/releases/download/v0.0.42/fn_0.0.42_linux_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "da421c1daf53122017d93fc8328912d862e3346b2a077c56b8f536678c3c609f"

      def install
        bin.install "fn"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/namespacelabs/foundation/releases/download/v0.0.42/fn_0.0.42_linux_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "2c4cd16666096787d2d38ae7d50d9fcd7992e34606769f25971f5655a9eee00e"

      def install
        bin.install "fn"
      end
    end
  end
end
