# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class Fn < Formula
  desc "Developer platform with a unified experience from development to production."
  homepage "https://namespacelabs.com/"
  version "0.0.43"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/namespacelabs/foundation/releases/download/v0.0.43/fn_0.0.43_darwin_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "dd3b0ab2e1704e8b6d6e6805e23080c17b314a4c5b02552223886bff0291d06d"

      def install
        bin.install "ns"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/namespacelabs/foundation/releases/download/v0.0.43/fn_0.0.43_darwin_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "304d7f5fdc32713a2b34a074ab755a3af7553ca5fddb5d86beb4e7e3ab4eba73"

      def install
        bin.install "ns"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/namespacelabs/foundation/releases/download/v0.0.43/fn_0.0.43_linux_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "1d2404d3feba7c6b4f6844acc303933f9b1161d143b98bdcee975cf50fa856ad"

      def install
        bin.install "ns"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/namespacelabs/foundation/releases/download/v0.0.43/fn_0.0.43_linux_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "1792ff2a0d622c5334b1df994a1ac1204738cd50bb1a02e2a9d22b49fa0e7481"

      def install
        bin.install "ns"
      end
    end
  end
end
