# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ns < Formula
  desc "Developer platform with a unified experience from development to production."
  homepage "https://namespacelabs.com/"
  version "0.0.44"

  on_macos do
    if Hardware::CPU.arm?
      url "https://ns-releases.s3.us-east-2.amazonaws.com/ns/v{.Version}/ns_0.0.44_darwin_arm64.tar.gz"
      sha256 "a8ac8cabdccc22718afbacd6fa95cae6068c8533d75723899386c7815ed8637c"

      def install
        bin.install "ns"
      end
    end
    if Hardware::CPU.intel?
      url "https://ns-releases.s3.us-east-2.amazonaws.com/ns/v{.Version}/ns_0.0.44_darwin_amd64.tar.gz"
      sha256 "d88ae8d2b973df89503c594bf7b239306bd9ec5fa531af50452f1db73940c566"

      def install
        bin.install "ns"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://ns-releases.s3.us-east-2.amazonaws.com/ns/v{.Version}/ns_0.0.44_linux_arm64.tar.gz"
      sha256 "1f95ff4c723c3f502811678e0d86f9d887420def3485479fe6b14ccfbc7886f1"

      def install
        bin.install "ns"
      end
    end
    if Hardware::CPU.intel?
      url "https://ns-releases.s3.us-east-2.amazonaws.com/ns/v{.Version}/ns_0.0.44_linux_amd64.tar.gz"
      sha256 "b706c3bbc2e818b0fbbf63a313005dacd8b1a4c9185eb565b41d0f33f76e33fe"

      def install
        bin.install "ns"
      end
    end
  end
end
